name       : btrfs-progs
version    : 5.13.1
release    : 36
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v5.13.1.tar.xz : 3d7e5a01e68fbaf485c5f1da15c6b8a7d1455fb57b6e75a706f8e2bb37f4f399
license    : GPL-2.0-only
homepage   : https://btrfs.wiki.kernel.org/index.php/Main_Page
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - pkgconfig(reiserfscore)
    - asciidoc
    - lzo-devel
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
