name       : btrfs-progs
version    : 4.15.1
release    : 12
source     :
    - https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v4.15.1.tar.xz : 67102ac0d6795f368acc94efaca29b6626d972638790a4a0c9f89a27cd543f96
license    : GPL-2.0-only
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(com_err)
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(uuid)
    - pkgconfig(zlib)
    - asciidoc
    - lzo-devel
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
