name       : btrfs-progs
version    : 6.3.1
release    : 49
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v6.3.1.tar.xz : 9ad98394c7936c3650445a134103a0db6ad3bf6f163917dfff49ff77614b3f14
license    : GPL-2.0-only
homepage   : https://btrfs.wiki.kernel.org/index.php/Main_Page
summary    :
  - Utilities for managing btrfs filesystems
  - libbtrfs: Library for managing btrfs filesystems
component  :
  - system.utils
  - libbtrfs: system.base
description:
  - Utilities for managing btrfs filesystems
  - libbtrfs: Library for managing btrfs filesystems
patterns   :
  - libbtrfs:
      - /usr/lib64/libbtrfs.so.*
      - /usr/lib64/libbtrfsutil.so.*
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - pkgconfig(reiserfscore)
    - asciidoc
    - lzo-devel
    - python-sphinx
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
