name       : btrfs-progs
version    : 6.3.3
release    : 51
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v6.3.3.tar.xz : 4be30015760270d081642cc0023a8bfee7cb657a2aa055644e6a56d68695b96e
license    : GPL-2.0-only
homepage   : https://btrfs.wiki.kernel.org/index.php/Main_Page
summary    :
    - Utilities for managing btrfs filesystems
    - libbtrfs : Library for managing btrfs filesystems
component  :
    - system.utils
    - libbtrfs : system.base
description:
    - Utilities for managing btrfs filesystems
    - libbtrfs : Library for managing btrfs filesystems
patterns   :
    - libbtrfs :
        - /usr/lib64/libbtrfs.so.*
        - /usr/lib64/libbtrfsutil.so.*
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - pkgconfig(reiserfscore)
    - asciidoc
    - lzo-devel
    - python-sphinx
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
