name       : btrfs-progs
version    : 4.8.2
release    : 6
source     :
    - https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v4.8.2.tar.xz : 81c023f519c8565b23eddb90e6d0eec2be63ee52e440708e418539dbaa635c5f
license    : GPL-2.0
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(com_err)
    - pkgconfig(blkid)
    - pkgconfig(uuid)
    - pkgconfig(zlib)
    - lzo-devel
    - asciidoc
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
