name       : btrfs-progs
version    : 4.20.1
release    : 19
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v4.20.1.tar.xz : 562f5d1ff1d17867c4c2be2768c653b62f1f257c42f9bb3e1a36380c02ec4fcd
license    : GPL-2.0-only
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(com_err)
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python-3.6)
    - pkgconfig(reiserfscore)
    - pkgconfig(uuid)
    - pkgconfig(zlib)
    - asciidoc
    - lzo-devel
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
