name       : btrfs-progs
version    : 4.16.1
release    : 13
source     :
    - https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v4.16.1.tar.xz : 013403fb67b17975b21408fa9eb7523b0ecf94f84f8a4397cf972e8e254d2246
license    : GPL-2.0-only
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(com_err)
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python-3.6)
    - pkgconfig(reiserfscore)
    - pkgconfig(uuid)
    - pkgconfig(zlib)
    - asciidoc
    - lzo-devel
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
