name       : btrfs-progs
version    : 4.8.5
release    : 8
source     :
    - https://cdn.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v4.8.5.tar.xz : d247b1c022aca5def3415bfa51e00c566cce36660a3ee517d4b6a1af911a08ef
license    : GPL-2.0
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(com_err)
    - pkgconfig(blkid)
    - pkgconfig(uuid)
    - pkgconfig(zlib)
    - lzo-devel
    - asciidoc
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
