name       : btrfs-progs
version    : 4.1.2
release    : 4
source     :
    - https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v4.1.2.tar.xz : 62db60c6a0868afb6302112cea54c756873bc30b826696b167ec03ecd61b2f12
license    : GPL-2.0
summary    : Utilities and library for managing btrfs filesystems
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(com_err)
    - pkgconfig(blkid)
    - pkgconfig(uuid)
    - pkgconfig(zlib)
    - lzo-devel
setup      : |
    %configure --disable-static --disable-documentation
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
