name       : btrfs-progs
version    : 6.1
release    : 44
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v6.1.tar.xz : 378bcafabdb64c453ac64fef3d4cf8c8d5e47f310319743f580667f9c1114657
license    : GPL-2.0-only
homepage   : https://btrfs.wiki.kernel.org/index.php/Main_Page
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - pkgconfig(reiserfscore)
    - asciidoc
    - lzo-devel
    - python-sphinx
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
