name       : btrfs-progs
version    : 5.11.1
release    : 29
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v5.11.1.tar.xz : e3aaccc4756ec4e5502cb2a9f85b67d52896644f4c3c0f88a6bc598c70bdebfe
license    : GPL-2.0-only
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - pkgconfig(reiserfscore)
    - asciidoc
    - lzo-devel
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
