name       : btrfs-progs
version    : 5.12.1
release    : 31
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v5.12.1.tar.xz : 950846fea454fb4b1c39f0fa454983644572df91df5c06047b335bf2d5473759
license    : GPL-2.0-only
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - pkgconfig(reiserfscore)
    - asciidoc
    - lzo-devel
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
