name       : btrfs-progs
version    : 5.4.1
release    : 25
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v5.4.1.tar.xz : f3e07fb248d608bdad5b63973513211de5daba47aaecfa44d29a836f6e7a9d69
license    : GPL-2.0-only
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - pkgconfig(reiserfscore)
    - asciidoc
    - lzo-devel
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
