name       : btrfs-progs
version    : 4.17.0
release    : 14
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v4.17.tar.xz : 82ca0ecf76350a1e3c6543fe220c0910e240511e663d51fc79c32bd0052c117c
license    : GPL-2.0-only
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(com_err)
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python-3.6)
    - pkgconfig(reiserfscore)
    - pkgconfig(uuid)
    - pkgconfig(zlib)
    - asciidoc
    - lzo-devel
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
