name       : btrfs-progs
version    : 5.3.1
release    : 23
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v5.3.1.tar.xz : bfa31ae60e54a068fd24e075a90b72f89b8e9006659273fbcecc2e1c790cda38
license    : GPL-2.0-only
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(com_err)
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python-3.6)
    - pkgconfig(reiserfscore)
    - pkgconfig(uuid)
    - pkgconfig(zlib)
    - asciidoc
    - lzo-devel
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
