name       : btrfs-progs
version    : 6.1.1
release    : 45
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v6.1.1.tar.xz : ca3a465d87200206e3a41d0f434f93cd222ca5325a2099a634dbdd23faeb6769
license    : GPL-2.0-only
homepage   : https://btrfs.wiki.kernel.org/index.php/Main_Page
summary    : Utilities and library for managing btrfs filesystems
component  : system.utils
description: |
    Utilities and library for managing btrfs filesystems
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - pkgconfig(reiserfscore)
    - asciidoc
    - lzo-devel
    - python-sphinx
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
